/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmsproject1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.text.DateFormat;
import java.text.ParseException;
//import java.text.SimpleDateFormat;
import java.util.Date;


//Read more: https://javarevisited.blogspot.com/2011/09/step-by-step-guide-to-convert-string-to.html#ixzz66wiG6fhf

/**
 *
 * @author Lenovo
 */
public class Query1 extends javax.swing.JFrame {

    /**
     * Creates new form Query1
     */
    public Query1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Year");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton1)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     /*   Connection con = null;
        Statement DataReq;
        ResultSet Res;
        
        try {
            con=DriverManager.getConnection(URL, USER,PASSWD);
            
            if(con!=null)
                System.out.println("Connected");
            
            //String dt=jTextField1.getText();
            
            String query = "SELECT COUNT(*) as CountCars FROM Payment WHERE Date LIKE '?'";
            PreparedStatement pstmt=con.prepareStatement(query);
              //pstmt.setString(1,jTextField1.getText());
              SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
     //String d = sdf.format(jTextField1.getText());
     Date d=sdf.parse(jTextField1.getText());
    /* DateFormat formatter = null;
     Date convertedDate = null;
       
     formatter =new SimpleDateFormat("yyyyMMdd");
        convertedDate =(Date) formatter.parse(yyyyMMdd);  
      pstmt.setString(1,convertedDate.toString());    */
/*     pstmt.setDate(1,d);
            pstmt.execute();
            JOptionPane.showMessageDialog(null,"Done!!","Messsage",JOptionPane.INFORMATION_MESSAGE);
          
            DataReq = con.createStatement();
            Res = DataReq.executeQuery(query);
            
            boolean rec = Res.next();
            
            String t ;
                                 
                      t=Res.getString("CountCars");
                
                    String Columns[] = {"CountCars"};
               
                    Object data[][]= {{t}};
                    
                                    
                   JTable jtab = new JTable(data,Columns);
                   JFrame jfrm = new JFrame("Cars information");
                   
                   jfrm.add(jtab);
                    
                  jfrm.setVisible(true);
                   jfrm.setSize(400,400);
                  
                   DataReq.close();    
            }
           
         catch(Exception e)
        {
            System.out.println(e);
        }
        finally
        {
            try{
            if(con!=null)
                    con.close();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }                                             */
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    static private String USER = "root";
    static private String PASSWD = "";
    static private String URL = "jdbc:mysql://localhost/Parking";
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Query1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Query1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Query1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Query1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Query1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
